apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  params:
    - name: app-name
      type: string
      default: cd-app

    - name: git-url
      type: string
      default: https://github.com/ilimturp-bot/ci-cd-final-project.git

    - name: git-revision
      type: string
      default: main

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: output

    - name: flake8
      runAfter:
        - git-clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose
      runAfter:
        - flake8
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      runAfter:
        - nose
      taskRef:
        name: buildah
